### ISSUE TITLE
Words that are misspelled are hard to read

### ISSUE THREAD

**Issue by DavidWiebe** [bluz71/vim-moonfly-colors#1]
In my .vimrc I have this line
`set spell spelllang=en_us`

Words that are misspelled look like this
![image](https://user-images.githubusercontent.com/12297853/27287817-1d04ec2e-54c2-11e7-8fc3-00400b7e1b5c.png)

**Comment by bluz71** [comment]
This was by design; I wanted to **clearly** highlight spelling errors the few times I did enable `spell`.

However, I can the annoyance from your perspective.

I've changed the colorscheme to highlight errors now, by default, using colored *undercurls*. That works well in GUI-based Vim's, but not so well in terminals (which is where my primary usage occurs).

However, a new option exists to enable the old reversed spell errors style:

```
let g:moonflySpellReversed = 1
```

In your case, don't set that. Just update and you should be good to go now.

Also, your screenshot looks like it is not using the *moonfly* color palette. If *gVim* / *Macvim* moonfly colors do not match Terminal *Vim* colors then your terminal is not configured correctly. In the terminal I recommend iTerm2 with Neovim and `set termguicolors`.

**Comment by DavidWiebe** [comment]
Thanks for the fix and the help with my colours.

termguicolors was causing issues in tmux. I have upgraded my tmux version and it fixed my issues. :)
