### ISSUE TITLE
The highlight color is too hard to see

### ISSUE THREAD

**Issue by duganchen** [bluz71/vim-moonfly-colors#10]
Do I have something misconfigured, or is the highlight color waaay too hard to see (it's very close to the background color), especially on translucent terminals?

**Comment by bluz71** [comment]
Search highlight color or visual selection color?

Search highlighting uses high contrast orange, this should be very obvious. If this is your issue then there will be a configuration issue of sorts.

Visual selection however uses low contrast grey, maybe this is your issue. Let me know which it is.

Note, moonfly is designed specifically for opaque terminals, aka no transparency, so it is not surprising that some colours may not look right.

**Comment by duganchen** [comment]
Visual selection color.

**Comment by bluz71** [comment]
Ok, I suspected as much.

Unfortunately the choice is deliberate since anything other than a low contrast color will look bad with syntax highlighting which I enable in visual selections. It is a delicate balancing act.

The upshot is that this color scheme really is designed for non transparent backgrounds.

Unfortunately the visual selection color will remain as is since this particular color has been in use for over six years and I still use it even today. Basically I like it how it is.

Your choices are to fork the color scheme and change the visual selection color, or use non transparency, or drop the color scheme and use something else that works better for you terminal setup.

I am sorry I could not be of more help. Hopefully you find a solution that works for you.

Best regards.

**Comment by bluz71** [comment]
Note, this is what visual selection looks like for me, contrast is reasonable for opaque background:

![moonfly_visual](https://user-images.githubusercontent.com/11382509/99615556-b74dd580-2a6f-11eb-9ce1-8b3ff4e40878.png)

Cheers.
