### ISSUE TITLE
Conceal highlight creates gaps in popups/floats

### ISSUE THREAD

**Issue by seandewar** [bluz71/vim-moonfly-colors#14]
![image](https://user-images.githubusercontent.com/6256228/113896057-7e659180-97c1-11eb-9086-40f2a0f29fdf.png)

Should be OK to remove the `ctermbg` and `guibg` attributes from `Conceal` to fix this.

You may also want to change the foreground colours too, they're the same as `Pmenu`'s background colour, which makes the placeholder characters invisible:

![image](https://user-images.githubusercontent.com/6256228/113896623-05b30500-97c2-11eb-974c-ec74122b772f.png)

Thanks!

**Comment by bluz71** [comment]
> Should be OK to remove the `ctermbg` and `guibg` attributes from `Conceal` to fix this.

Just removing those options does not work since (Neo)Vim will then set its own background color, which is probably the reason I set the background colors to begin with.

This instead appears to work and hopefully should also solve your issue as well:

```viml
exec 'highlight Conceal ctermbg=none ctermfg=235 guibg=none guifg=' . s:grey235
```

Can you test the latest update.

> You may also want to change the foreground colours too, they're the same as Pmenu's background colour, which makes the placeholder characters invisible

No, `Conceal` was deliberately styled in low contrast for indent guides and the like. The moonfly theme is designed specifically for a background color of `#080808`. Popups and Floats are using `Pmenu` color far too often and it breaks themes in subtle ways. If I change `Conceal` for `Pmenu` backgrounds then it will appear far too bright on the standard theme background.

The better solution is for popups and floats to use the standard theme background colour with a border all around as seen in these fuzzy finder floating window screenshots:

![fzf](https://user-images.githubusercontent.com/11382509/113969604-9ea45780-9878-11eb-9f91-55c4ac537e96.png)

![Telescope](https://user-images.githubusercontent.com/11382509/113969636-aebc3700-9878-11eb-9777-533c9936224a.png)

For now, `Conceal` will remain the colour it is, the lesser of two evils.

Cheers.

**Comment by seandewar** [comment]
This is a fine compromise and fixes the gaps, thanks! 

My experience with creating color schemes is quite limited, so I appreciate the detailed response and clarifications. 

Awesome work as always! 😁

**Comment by bluz71** [comment]
I am pleased the initial problem is fixed.

Best regards.

**Comment by bluz71** [comment]
@seandewar,

There has been some enhancements done by the Neovim team with regard to LSP floating window style.

Users can now specify borders. So this is the floating window style I now use for LSP hover operations:

![LSP_Hover](https://user-images.githubusercontent.com/11382509/116053759-5f6e6700-a6be-11eb-9922-76566f0c8d30.png)

Two tweaks needed, first you must tell the moonfly theme to use custom floating window colors:

```viml
let g:moonflyNormalFloat = 1
```

And, you should make use of Neovim LSP's floating window border style (very recent Neovim 0.5 version required):

```lua
vim.lsp.handlers["textDocument/hover"] = vim.lsp.with(
   vim.lsp.handlers.hover, {
     border = {
       {'┌', 'FloatBorder'},
       {'─', 'FloatBorder'},
       {'┐', 'FloatBorder'},
       {'│', 'FloatBorder'},
       {'┘', 'FloatBorder'},
       {'─', 'FloatBorder'},
       {'└', 'FloatBorder'},
       {'│', 'FloatBorder'}
     }
   }
  )
```

Cheers.

**Comment by seandewar** [comment]
Thanks for adding this option. :)

I use vim-lsp atm (I still use Vim) and I don't think Nvim float borders can be configured yet with it.
I sometimes contribute to Nvim, so maybe I'll be inspired to fully convert my config one day. :smile:

Cheers!

**Comment by bluz71** [comment]
Oh sorry, I genuinely that you were using Neovim LSP. My tweaks are targeted specifically to Neovim LSP with its new border option.
