### ISSUE TITLE
Warning parts is now hard to see

### ISSUE THREAD

**Issue by teenjuna** [bluz71/vim-moonfly-colors#19]
Hi! I really like your theme, but after some (I don't know which exactly) update the "warnings" parts of my code became very difficult to see:
![image](https://user-images.githubusercontent.com/53595243/132006512-a52ab5cb-a377-49f3-9a2d-d31029b72408.png)

Previously they were just underlined.

**Comment by bluz71** [comment]
Which diagnostic system are you using?

Please provide as much detail as possible for me to repeat. A test file as well.

Note, I do know that CoC does its own highlighting, which causes issues, as an example.

**Comment by teenjuna** [comment]
I'm indeed using CoC with the coc-rust-analyzer. Here is a test file:
```rust
fn main() {
    let unused_variable = 1;
    println!("Hello world!");
}
```
Which looks like this:

![image](https://user-images.githubusercontent.com/53595243/132028021-0c2d6390-2fd6-4761-8313-50d97ef573af.png)

Do you need me to write instructions on how to setup Rust project in case you aren't familiar with the matter? Do you need to see my init.vim file? I'll be happy to provide anything that might help!

**Comment by bluz71** [comment]
I had a user, with my other nightly issue, note a similar issue.

I believe CoC has changed, not my themes.

CoC is applying semantic, LSP-based highlighting over the top. We don't want that.

I need to explore this problem. Either we need to find the CoC option to turn this off, or I need to change my themes a little bit.

I myself use Neovim with its own LSP if that is of interest.

Let's fix this.

**Comment by teenjuna** [comment]
Yeah, I guess it's worth investigating. I should mention that other themes I've checked aren't affected by this. Although some of them do something similar: they change the background color of text, which makes the code less readable due to the lack of contrast.

I also found that this is not only related to warnings. In Python, for example, a warning will look just fine. Errors, however, do differ (between each other too...):

![image](https://user-images.githubusercontent.com/53595243/132078596-a4ab9790-ee24-4dfc-873c-4d694df1f351.png)

The only difference between this errors is that the first one has some cyan annotation on hover:

![image](https://user-images.githubusercontent.com/53595243/132078626-ad9b6764-b923-441d-97f5-e730b6017122.png)

Whereas the other two don't:

![image](https://user-images.githubusercontent.com/53595243/132078633-d58e576f-bc47-4999-87bc-a510a85067fb.png)

**Comment by bluz71** [comment]
Some research indicates that CoC, during July, implemented it's own highlighting subsystem as seen here:

- https://github.com/neoclide/coc.nvim/commit/51082a7ff98e0c82abb9c95404a9cbdf9d0e9262
- https://github.com/neoclide/coc.nvim/pull/3188

Your issue here is basically the same as [this issue also reported to my other colorscheme](https://github.com/bluz71/vim-nightfly-guicolors/issues/25).

I will soon commit a fix for `CocUnusedHighlight` which will link it back to White (not Faded). One by one we should fix all problems.

I don't agree with CoC implementing its own highlighting subsystem. If there is a switch to turn it off I would ultimately recommend that. But first lets fix all obvious problems.

**Comment by bluz71** [comment]
Please update and try again.

I have now linked `CocUnusedHighlight` to White.

**Comment by bluz71** [comment]
Let me know if there are other Coc highlight issues that need fixed.

If using Vim or non-Treesitter Neovim you can place your cursor over the bad highlight and do `:echo synIDattr(synID(line('.'), col('.'), 1), 'name')`.

If using Neovim Treesitter then install [nvim-treesitter/playground](https://github.com/nvim-treesitter/playground) and then do `:TSHighlightCapturesUnderCursor`.

Cheers.

**Comment by teenjuna** [comment]
No, I don't see any issues at the moment, your last commit fixed the issue. Thank you very much! I'll remember the treesitter/playground method in case I'll need to report something in the future.

**Comment by bluz71** [comment]
Ok, that is great news. Don't hesitate to hit me up if something else needs fixing.

Best of luck.

**Comment by oblitum** [comment]
I feel it's necessary to interject to enlighten the case, for everyone's benefit, but specially for those that subscribe to this issue (except for the colorscheme author). I see this message quite possibly being deleted, tagged as spam, and such, but at least I know it'll reach you by email. So without further ado.

First, this is not a coc.nvim issue, it's an issue with this colorscheme, and specially with the author's confuse interpretation of vim's conceal feature, it's so much so that the problem not  only echoes in coc.nvim, it replicates in many other plugins that rely on vim conceal, like [in vimtex](https://0x0.st/-nES.gif), vim-haskellConcealPlus, julia-vim, and many others that take advantage of vim's feature of **concealing chars for other chars**.

I've been in chat with the colorscheme author and **the key issue here is their practice of picking the highlighting group for concealed chars to apply an additional level of fake concealing** (by means of low contrast) **on what is already concealed** (the conceal feature conceals chars for others, it's not about hiding with contrast!). TL;DR: the `Conceal` highlighting group is for **highlighting** what's **concealed**, _it's not_ for fake concealing (that's quite a stretch).

The author's response has been simply to deny this fact, to the extent of quoting a dictionary on the meaning of "conceal" and tagging other plugins as "moronic" in what they do.
