### ISSUE TITLE
Plans on porting for bufferline.

### ISSUE THREAD

**Issue by alok8bb** [bluz71/vim-moonfly-colors#24]
Hello, thanks for creating this awesome color-scheme. I wanted to know if you have any plans for porting this theme for [bufferline.nvim](https://github.com/akinsho/bufferline.nvim). 

Thanks.

**Comment by bluz71** [comment]
Last time I looked bufferline had many highlight groups, which confused me. Since no one ever asked for bufferline, I let it go, especially since the similar [barbar](https://github.com/romgrk/barbar.nvim) was already integrated.

How important is bufferline support to you?
Why do you use it instead of barbar?

Just curious.
If it's very important to you then I will have a look again.

**Comment by alok8bb** [comment]
I actually tried barbar.nvim and it worked pretty fine but the integration with nvim-tree was having some offset issues and it wasn't able to set layout, probably a bug. 

bufferline.nvim works perfectly with [nvim-tree](https://github.com/kyazdani42/nvim-tree.lua) and nowadays I've seen many people use it because its highly customizable. 

![image](https://user-images.githubusercontent.com/73450969/180373071-37111bb5-4bfd-45bc-a2dc-351615bbdc1c.png)
This is how current moonfly looks with Bufferline.

![image](https://user-images.githubusercontent.com/73450969/180373259-2ad3be43-3212-4e3e-978e-a2b20d2b04be.png)
And this is [nightfox](https://github.com/EdenEast/nightfox.nvim) for example.

Please look into it, if you are free.  
Also a suggestion: I think a more darker color for NvimTree bg, Bufferline bg and Statusline bg would look better (like in nightfox), as it'll be more easier differentiate between tree and editor as compared to a simple border. :P

**Comment by bluz71** [comment]
Ok, I will have a look at bufferline, and integrate it into moonfly and nightfly. May take a few days or so.

The `StatusLine` bg color is a long-term color choice (dating back to 2013). That is not going to change; personally I prefer the statusline being brighter than the edit text, not darker. I do know some modern themes go the other way.

Note, you can override theme colors as follows, create a file `after/plugin/colorscheme.vim` with content:

```viml
if g:colors_name == 'moonfly'
    highlight! link StatusLine LineNr
endif
```

For example.

Cheers.

**Comment by bluz71** [comment]
In your case you can also choose the thickness of the separators with the `moonflyWinSeparator` option, for example, this may look nicer:

```lua
vim.g.moonflyWinSeparator = 2
vim.opt.fillchars = { horiz = '━', horizup = '┻', horizdown = '┳', vert = '┃', vertleft = '┫', vertright = '┣', vertho
```

**Comment by alok8bb** [comment]
> Why closed? You still want bufferline?

Yeah, I thought it's better to close as you'll add it now probably. 😄

**Comment by bluz71** [comment]
Ok, but I'll reopen until the job is done.

Cheers.

**Comment by bluz71** [comment]
Ok, I have added support for Bufferline.nvim.

This was **extraordinarily difficult**. By far the hardest plugin to support color-scheme wise. Bufferline.nvim has a ridiculous number of highlight groups, married up with no documentation about these groups. Now I remember why I didn't add support for it previously. This was painful.
 
Stylistically, moonfly support for Bufferline.nvim is not ideal since Bufferline appears to prefer tablines that are darker than the edit screen; which is not possible with moonfly since the edit screen is already dark. A best effort done. There are probably still some case where the colors are not quite correct, LSP maybe? To-be-determined.

Note, I've also added Bufferline.nvim support to my other colorscheme, [nightfly](https://github.com/bluz71/vim-nightfly-guicolors).
