### ISSUE TITLE
`TODO` word is not visible

### ISSUE THREAD

**Issue by shayanh** [bluz71/vim-moonfly-colors#28]
When the cursor is on the same line as the `TODO` word, `TODO` becomes too dark and almost impossible to see.

Cursor is one line above the `TODO` word. `TODO` is visible. ✅
<img width="569" alt="Screen Shot 2022-09-17 at 4 32 55 PM" src="https://user-images.githubusercontent.com/1623278/190879628-b2781901-c478-4df1-9a22-b120aa995309.png">

Cursor is on the same line as the `TODO` word. `TODO` is not visible. ❌
<img width="556" alt="Screen Shot 2022-09-17 at 4 33 09 PM" src="https://user-images.githubusercontent.com/1623278/190879668-9648e19e-d1b2-403c-a983-e49773ec10fe.png">

I'm using moonfly on commit `448df20e1d24cb4d6a32f71de3b1c9d8ea84cbfd`, Vim 9.0.50, iTerm2 3.4.16 and macOS 12.6.

**Comment by bluz71** [comment]
Thanks for bringing this to my attention.

This issue illustrates a bad interaction between `TODO` highlighting and `cursorline`; I don't use `cursorline` myself hence I did not spot this issue (it's probably been a problem for a long time).

I've now changed to a more subtle `TODO` highlight style (yellow text instead of a yellow block) that looks better and avoids this issue.

Cheers.

**Comment by shayanh** [comment]
Thanks for the quick fix!
