### ISSUE TITLE
Neogit Issue

### ISSUE THREAD

**Issue by jacknicklenson** [bluz71/vim-moonfly-colors#42]
Hi,
Thanks for the nice theme but with the neogit plugin, it hard to distinguish the hunk texts. :(

![Ekran görüntüsü 2023-07-15 232252](https://github.com/bluz71/vim-moonfly-colors/assets/90291236/9084b51e-2fec-48e6-92b4-92fdeb7956a0)

**Comment by szymonruszala** [comment]
Just use other plugin for git. 👍

**Comment by bluz71** [comment]
Since Tokyo Night, Catppuccin and Nightfox themes all support Neogit, this theme should as well.

Stay tuned.

**Comment by bluz71** [comment]
@jacknicklenson,

Please update and test.
Let me know if the colors solve your issue (or not).
If not, let me know which exact highlight group is still an issue.
I could not fully test Neogit since I didn't setup diffview.
I just took Tokyo Night's Neogit colors and tweaked them for this theme.

Cheers.

**Comment by jacknicklenson** [comment]
It's been solved. Thx a lot.


![Ekran görüntüsü 2023-07-16 190150](https://github.com/bluz71/vim-moonfly-colors/assets/90291236/10aa6870-daff-453e-96a6-39eae1f97c24)
