### ISSUE TITLE
Feature Request: Porting to VScode 

### ISSUE THREAD

**Issue by huyhoang8398** [bluz71/vim-moonfly-colors#49]
I love this colorscheme, but sometime when we do pair programming, we usually using vscode
Is this possible to port this theme into vscode?

**Comment by bluz71** [comment]
It will require someone with the time and passion to do that.

I solely use Neovim (and occasionally Vim) for all my editing. Hence, I am not the person for the task since I have never used VSCode. Sorry, I am not up to the task.

Maybe [moonlit](https://github.com/atomiks/moonlight-vscode-theme) or [nightowl](https://github.com/sdras/night-owl-vscode-theme) themes are reasonable alternatives?

**Comment by huyhoang8398** [comment]
Thanks,
I think it's time for me to learn about vscode theme stuffs

**Comment by bluz71** [comment]
ChatGPT may well prove useful in this task.

I converted from Bash to Fish Shell in large part due to ChatGPT.
